### ISSUE TITLE
Configure with fixtures is not working

### ISSUE THREAD

**Issue by matejzero** [voxpupuli/voxpupuli-acceptance#69]
I tried to migrate to voxpupuli-acceptance and use `configure_beaker(modules: :fixtures)` to configure/install modules, but it doesn't seem to work.

Rake checks out modules to fixtures, but when it comes to installing modules, it only installs modules which were checkout via github, but not the main module which is symlinked.

It seems to work if I have a `metadata.json` file in module, but most of my modules don't as we don't need them. Is that a hard requirement?

_.fixtures.yml_:
```
fixtures:
  repositories:
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib
    yumrepo_core:
      repo: "https://github.com/puppetlabs/puppetlabs-yumrepo_core.git"
      puppet_version: ">= 6.0.0"
  symlinks:
    sshd: "#{source_dir}"
```

```
bash-4.4$ bundle exec rake beaker
I, [2023-09-22T11:04:43.082887 #3613450]  INFO -- : Creating symlink from spec/fixtures/modules/sshd to /opt/ssd/gitlab-runner/builds/LwWQYZLE/4/puppet/sshd
Cloning into 'spec/fixtures/modules/yumrepo_core'...
Cloning into 'spec/fixtures/modules/stdlib'...

...

almalinux8-puppet6 11:06:20$ mktemp -d
  /tmp/tmp.Mk8ocJqtwb

almalinux8-puppet6 executed in 0.05 seconds
localhost $ scp /tmp/d20230922-3613483-plpuun/puppetlabs-yumrepo_core-2.0.0.tar.gz almalinux8-puppet6:/tmp/tmp.Mk8ocJqtwb/puppetlabs-yumrepo_core-2.0.0.tar.gz {:ignore => }

almalinux8-puppet6 11:06:20$ puppet module install --force --ignore-dependencies '/tmp/tmp.Mk8ocJqtwb/puppetlabs-yumrepo_core-2.0.0.tar.gz'
  Notice: Preparing to install into /etc/puppetlabs/code/environments/production/modules ...
  Notice: Installing -- do not interrupt ...
  /etc/puppetlabs/code/environments/production/modules
  └── puppetlabs-yumrepo_core (v2.0.0)

almalinux8-puppet6 executed in 1.37 seconds
localhost $ scp /tmp/d20230922-3613483-plpuun/puppetlabs-stdlib-9.3.0.tar.gz almalinux8-puppet6:/tmp/tmp.Mk8ocJqtwb/puppetlabs-stdlib-9.3.0.tar.gz {:ignore => }

almalinux8-puppet6 11:06:22$ puppet module install --force --ignore-dependencies '/tmp/tmp.Mk8ocJqtwb/puppetlabs-stdlib-9.3.0.tar.gz'
  Notice: Preparing to install into /etc/puppetlabs/code/environments/production/modules ...
  Notice: Installing -- do not interrupt ...
  /etc/puppetlabs/code/environments/production/modules
  └── puppetlabs-stdlib (v9.3.0)
```
